baseURL = 'https://tmax818.com/'
languageCode = 'en-us'
title = "Mr. M's Science Page"
theme = 'KeepIt'

[author]
  name = "Mr. M"
  homepage = "https://tmax818.com/"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
[params]
  math = true